version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: itext7
    versions:
    - 7.1.14
  - dependency-name: Portable.BouncyCastle
    versions:
    - 1.8.9
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
