//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfAnnotator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfAnnotator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the
        ///a
        ///is
        ///was
        ///in
        ///of
        ///to
        ///i
        ///for
        ///are
        ///we
        ///he
        ///and
        ///not
        ///it
        ///on
        ///with
        ///be
        ///they
        ///will
        ///at
        ///this
        ///that
        ///she
        ///an
        ///by
        ///you
        ///also
        ///were
        ///have
        ///has
        ///it’s
        ///can
        ///from
        ///about
        ///just
        ///but
        ///your
        ///very
        ///all
        ///my
        ///said
        ///his
        ///good
        ///it&apos;s
        ///had
        ///do
        ///like
        ///no
        ///her
        ///really
        ///would
        ///our
        ///as
        ///them
        ///time
        ///what
        ///great
        ///there
        ///should
        ///need
        ///me
        ///so
        ///did
        ///want
        ///never
        ///been
        ///their
        ///here
        ///into
        ///now
        ///don’t
        ///always
        ///could
        ///some
        ///new
        ///out
        ///got
        ///two
        ///still
        ///how
        ///him
        ///love
        ///i’m
        ///up
        ///people
        ///get
        ///work
        ///know
        ///game
        ///too
        ///died
        ///made
        ///lot
        ///tha [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CommonEnglishWords {
            get {
                return ResourceManager.GetString("CommonEnglishWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die der
        ///die
        ///ist
        ///in
        ///das
        ///den
        ///auf
        ///ein
        ///eine
        ///werden
        ///sie
        ///und
        ///mit
        ///von
        ///für
        ///des
        ///wird
        ///sich
        ///sind
        ///es
        ///nicht
        ///dem
        ///wurde
        ///auch
        ///im
        ///an
        ///war
        ///zu
        ///hat
        ///aus
        ///einen
        ///um
        ///er
        ///einer
        ///bei
        ///noch
        ///einem
        ///am
        ///über
        ///nach
        ///wir
        ///prozent
        ///gibt
        ///wurden
        ///nur
        ///vor
        ///haben
        ///durch
        ///euro
        ///ich
        ///kann
        ///aber
        ///sei
        ///zum
        ///soll
        ///keine
        ///diese
        ///zur
        ///können
        ///hatte
        ///waren
        ///wieder
        ///was
        ///hier
        ///sehr
        ///dann
        ///dies
        ///schon
        ///sein
        ///habe
        ///als
        ///wie
        ///ab
        ///so
        ///immer
        ///geht
        ///doch
        ///steht
        ///neue
        ///unter
        ///mehr
        ///liegt
        ///gegen
        ///nun
        ///uns
        ///muss
        ///eines
        ///jedoch
        ///jet [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CommonGermanWords {
            get {
                return ResourceManager.GetString("CommonGermanWords", resourceCulture);
            }
        }
    }
}
